name: Update Permission Inputs

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-permission-inputs:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: 'feat: update permission inputs'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - name: Install dependencies
        run: npm ci
      - name: Run permission inputs update script
        run: node scripts/update-permission-inputs.js
      - name: Commit changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
      - name: Update PR title
        if: github.event_name == 'pull_request' && steps.auto-commit.outputs.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --title "${{ env.COMMIT_MESSAGE }}"
